version: 2.1


workflows:
  build_deploy:
    jobs:
      - build-deploy

jobs:

  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: build and push docker image to heroko
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_APP_KEY = ${HEROKU_APP_KEY} heroku container:login
            HEROKU_APP_KEY = ${HEROKU_APP_KEY} heroku container:push -a bibloteca web
            HEROKU_APP_KEY = ${HEROKU_APP_KEY} heroku container:release -a bibloteca web
            
            

   
   





