version: 2.1



jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew bootJar
      - persist_to_workspace:
          root: ./
          paths:
            - build/
            - .gradle/
  test:

    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    steps:
      - checkout

      - run: ./gradlew test

      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test


  deploy:
    steps:
      - checkout
      - run:
          name: build and push docker image to heroko
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_APP_KEY = ${HEROKU_APP_KEY} heroku container:login
            HEROKU_APP_KEY = ${HEROKU_APP_KEY} heroku container:push -a bibloteca web
            HEROKU_APP_KEY = ${HEROKU_APP_KEY} heroku container:release -a bibloteca web
            
            

    docker:
      -
    machine: true




workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
